PROCESSOR 16f877
INCLUDE <p16f877.inc> 

	ORG 0
	GOTO INICIO 
	ORG 5

INICIO:
	BCF STATUS,RP1		; RP1 = 0
	BSF STATUS,RP0		; RP0 = 1, MUEVE AL BANCO 1
	MOVLW 0X20			; W <-- 0X20
	MOVWF FSR			; MUEVE CONTENIDO DE W A FSR. FSR = 0X20
	
LOOP:
	MOVLW 0X5F			; W <-- 0X5F
	MOVWF INDF			; MUEVE CONTENIDO DE W AL REGISTRO QUE APUNTA FSR
	INCF FSR			; INCREMENTO FSR
	BTFSS FSR,6			; SI EL BIT 6 DE FSR ES 1, SALTA
	GOTO LOOP			; SI NO, REGRESA A LOOP
	GOTO $

END
